<?php

namespace LaLigaBundle\Repository;

/**
 * EquiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function buscarClubs()
    {
        $em    = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('c')
                ->from('LaLigaBundle:Club', 'c')
                ->where('c.borrado = 0');
        
        return $query->getQuery()->getResult();
    }
    

}
