<?php

namespace LaLigaBundle\Repository;

/**
 * JugadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
